# Business Exposure Modelling – Sprint 1

## Assumptions
- USD Amount: $10,000
- Base USD–INR Rate: 83
- IT Firm INR Costs: ₹6,00,000

In [2]:
import pandas as pd

# -----------------------------
# 1. Define Business Personas
# -----------------------------

data = {
    "Business Type": ["Importer", "Exporter", "IT Firm"],
    "USD Amount": [10000, 10000, 10000],
    "INR Costs": [None, None, 600000]
}

personas = pd.DataFrame(data)
personas

  Business Type  USD Amount  INR Costs
0      Importer       10000        NaN
1      Exporter       10000        NaN
2       IT Firm       10000   600000.0

In [3]:
# -----------------------------
# 2. Set Exchange Rates
# -----------------------------

current_rate = 83
rate_1_percent = current_rate * 0.01
rate_5_percent = current_rate * 0.05

rate_1_percent, rate_5_percent

(0.8300000000000001, 4.15)

In [4]:
# -----------------------------
# 3. Margin Impact Calculation
# -----------------------------

usd_amount = 10000

margin_impact = pd.DataFrame({
    "Scenario": ["1% Change", "5% Change"],
    "Rate Change (₹)": [rate_1_percent, rate_5_percent],
    "Impact on ₹": [usd_amount * rate_1_percent, usd_amount * rate_5_percent]
})

margin_impact

    Scenario  Rate Change (₹)  Impact on ₹
0  1% Change             0.83       8300.0
1  5% Change             4.15      41500.0

In [5]:
# -----------------------------
# 4. Break-even Exchange Rate
# -----------------------------

break_even_data = {
    "Business Type": ["Importer", "Exporter", "IT Firm"],
    "INR Cost / Revenue": [850000, 750000, 600000],
    "USD Amount": [10000, 10000, 10000]
}

break_even_df = pd.DataFrame(break_even_data)
break_even_df["Break-even Rate"] = break_even_df["INR Cost / Revenue"] / break_even_df["USD Amount"]

break_even_df

  Business Type  INR Cost / Revenue  USD Amount  Break-even Rate
0      Importer              850000       10000             85.0
1      Exporter              750000       10000             75.0
2       IT Firm              600000       10000             60.0

In [6]:
# -----------------------------
# 5. Sensitivity Analysis (₹0.50 movement)
# -----------------------------

rates = [82.5, 83.0, 83.5]

sensitivity = pd.DataFrame({
    "Exchange Rate": rates,
    "Importer Impact (₹)": [(r - current_rate) * usd_amount for r in rates],
    "Exporter Impact (₹)": [(current_rate - r) * usd_amount for r in rates],
    "IT Firm Profit (₹)": [(usd_amount * r) - 600000 for r in rates]
})

sensitivity

   Exchange Rate  Importer Impact (₹)  Exporter Impact (₹)  IT Firm Profit (₹)
0           82.5              -5000.0               5000.0            225000.0
1           83.0                  0.0                  0.0            230000.0
2           83.5               5000.0              -5000.0            235000.0

## Scenario-Based Business Exposure Analysis

## Assumptions

The following assumptions are used for business exposure modelling:

- USD exposure per transaction: $10,000  
- Base USD–INR exchange rate: 83  
- IT Services Firm INR operational costs: ₹6,00,000  
- Scenarios are defined to represent favorable, neutral, and adverse currency movements  

All values are assumed for academic demonstration and sensitivity analysis purposes.

In [7]:
import pandas as pd

# Base assumptions
usd_amount = 10000
base_rate = 83
it_costs = 600000

usd_amount, base_rate, it_costs

(10000, 83, 600000)

## Scenario-Based Exposure Analysis

To move beyond single-point estimation, business exposure is evaluated under
multiple realistic exchange rate scenarios.

In [8]:
# Define scenarios
scenarios = pd.DataFrame({
    "Scenario": ["Favorable", "Neutral", "Adverse"],
    "USD_INR_Rate": [82, 83, 85]
})

# Importer exposure (loss when rate increases)
scenarios["Importer_Impact_INR"] = usd_amount * (scenarios["USD_INR_Rate"] - base_rate)

# Exporter exposure (loss when rate decreases)
scenarios["Exporter_Impact_INR"] = usd_amount * (base_rate - scenarios["USD_INR_Rate"])

# IT firm profit
scenarios["IT_Firm_Profit_INR"] = (usd_amount * scenarios["USD_INR_Rate"]) - it_costs

scenarios

,Scenario,USD_INR_Rate,Importer_Impact_INR,Exporter_Impact_INR,IT_Firm_Profit_INR
0,Favorable,82,-10000,10000,220000
1,Neutral,83,0,0,230000
2,Adverse,85,20000,-20000,250000

## Profit-at-Risk (PaR) Analysis

Profit-at-Risk represents the maximum expected loss faced by a business
under an adverse exchange rate movement.

In [9]:
# Identify adverse scenario
adverse_rate = scenarios.loc[scenarios["Scenario"] == "Adverse", "USD_INR_Rate"].values[0]

profit_at_risk = pd.DataFrame({
    "Business Type": ["Importer", "Exporter", "IT Services Firm"],
    "Profit_at_Risk_INR": [
        usd_amount * (adverse_rate - base_rate),          # Importer loss
        usd_amount * (base_rate - adverse_rate),          # Exporter loss
        (usd_amount * base_rate) - (usd_amount * adverse_rate)  # IT firm downside
    ]
})

profit_at_risk

      Business Type  Profit_at_Risk_INR
0          Importer               20000
1          Exporter              -20000
2  IT Services Firm              -20000

## Comparative Sensitivity Analysis

This analysis compares how sensitive different business types are to a
₹1 movement in the USD–INR exchange rate.

In [10]:
# Sensitivity per ₹1 movement
sensitivity = pd.DataFrame({
    "Business Type": ["Importer", "Exporter", "IT Services Firm"],
    "Impact_per_1_INR_Move": [
        usd_amount,            # Importer
        usd_amount,            # Exporter
        usd_amount             # IT firm revenue sensitivity
    ]
})

# Add qualitative risk levels
sensitivity["Risk_Level"] = ["High", "Medium", "High"]

sensitivity

      Business Type  Impact_per_1_INR_Move Risk_Level
0          Importer                  10000       High
1          Exporter                  10000     Medium
2  IT Services Firm                  10000       High

## Business Interpretation & Decision Implications

### Importer
Importers are highly exposed to INR depreciation. Even a ₹1 increase in the
USD–INR rate results in a ₹10,000 increase in costs. Under adverse scenarios,
importers face significant profit-at-risk, indicating the need for early
currency conversion or hedging strategies.

### Exporter
Exporters benefit from INR depreciation but face downside risk when the INR
strengthens. While exporters can gain in favorable scenarios, adverse movements
can reduce INR realizations, making timing decisions critical.

### IT Services Firm
IT services firms are structurally sensitive to exchange rate movements due to
USD-denominated revenues and INR-denominated costs. Although revenue increases
with higher USD–INR rates, firms with thin margins face substantial downside risk
if the currency moves unfavorably.

### Summary
The analysis highlights that exchange rate exposure is asymmetric across
business types. Importers and IT firms exhibit high sensitivity, while exporters
face conditional risk depending on currency direction. These insights form a
critical input for risk scoring and FX decision recommendation modules in
subsequent sprints.

## Integration with Subsequent Modules

The Business Exposure Modelling module outputs the following metrics:

- Scenario-based exposure values
- Profit-at-Risk estimates
- Sensitivity per unit exchange rate movement
- Break-even and downside thresholds

These outputs serve as direct inputs to:
- FX Risk Scoring Engine (Sprint 4)
- Decision Recommendation Engine (Sprint 5)

## Break-Even and Pain-Threshold Analysis

While scenario-based exposure quantifies potential gains or losses, businesses
also require decision boundaries to determine when exchange rate movements
become unacceptable.

- **Break-even rate**: Exchange rate at which profit impact is zero
- **Pain-threshold rate**: Exchange rate beyond which losses are considered
  operationally unacceptable

These thresholds help convert exposure values into actionable business signals.

In [11]:
# Break-even and pain-threshold definitions
thresholds = pd.DataFrame({
    "Business": ["Importer", "Exporter", "IT Services Firm"],
    "Break_Even_Rate": [83, 83, 83],
    "Pain_Threshold_Rate": [85, 81, 82]
})

thresholds

           Business  Break_Even_Rate  Pain_Threshold_Rate
0          Importer               83                   85
1          Exporter               83                   81
2  IT Services Firm               83                   82

## Exposure Zone Classification

To simplify decision-making, exchange rate outcomes are classified into
qualitative exposure zones:

- **Safe**: No immediate business action required
- **Warning**: Monitoring or partial intervention required
- **Danger**: Immediate action required to mitigate losses

This classification supports intuitive business interpretation without
introducing automated decision rules.

In [12]:
# Exposure zone classification for Importer
def importer_exposure_zone(rate):
    if rate <= 83:
        return "Safe"
    elif rate < 85:
        return "Warning"
    else:
        return "Danger"

scenarios["Importer_Exposure_Zone"] = scenarios["USD_INR_Rate"].apply(importer_exposure_zone)

scenarios

,Scenario,USD_INR_Rate,Importer_Impact_INR,Exporter_Impact_INR,IT_Firm_Profit_INR,Importer_Exposure_Zone
0,Favorable,82,-10000,10000,220000,Safe
1,Neutral,83,0,0,230000,Safe
2,Adverse,85,20000,-20000,250000,Danger

## Business Risk Prioritisation

Not all businesses face exchange rate risk with equal severity.
Based on exposure magnitude, sensitivity, and profit dependency,
business types can be prioritised for risk attention.

This prioritisation is qualitative and intended to guide downstream
risk scoring and decision recommendation modules.

In [14]:
risk_priority = pd.DataFrame({
    "Business": ["Importer", "IT Services Firm", "Exporter"],
    "Risk_Priority_Rank": [1, 2, 3],
    "Justification": [
        "Direct increase in INR costs with USD appreciation",
        "High margin sensitivity due to USD revenue and INR costs",
        "Risk is conditional on exchange rate direction"
    ]
})

risk_priority

,Business,Risk_Priority_Rank,Justification
0,Importer,1,Direct increase in INR costs with USD apprecia...
1,IT Services Firm,2,High margin sensitivity due to USD revenue and...
2,Exporter,3,Risk is conditional on exchange rate direction

## Outputs for Downstream Risk Scoring and Recommendation Modules

The Business Exposure Modelling module produces the following structured outputs
before probabilistic risk scoring or forecasting is applied:

- Scenario-wise exposure values
- Profit-at-Risk (PaR) estimates
- Sensitivity per ₹1 exchange rate movement
- Break-even and pain-threshold rates
- Exposure zone classifications
- Business risk prioritisation

These outputs act as deterministic, business-grounded inputs to the
risk scoring engine and decision recommendation framework developed
in subsequent sprints.

## Multi-Currency Exposure Extension

The exposure modelling framework is extended to support multiple foreign
currencies commonly used by Indian businesses: USD, GBP, EUR, and JPY.

The same business logic is applied consistently across currencies, allowing
comparative exposure analysis without duplicating code.

In [1]:
import pandas as pd

# USD equivalent exposure amount
fx_amount = 10000
it_costs = 600000

# Base exchange rates (Foreign Currency → INR)
base_rates = {
    "USD": 83.0,
    "GBP": 105.0,
    "EUR": 90.0,
    "JPY": 0.56
}

base_rates

{'USD': 83.0, 'GBP': 105.0, 'EUR': 90.0, 'JPY': 0.56}

In [2]:
# Scenario multipliers
scenario_adjustments = {
    "Favorable": -0.02,   # ~2% INR appreciation
    "Neutral": 0.00,
    "Adverse": 0.03       # ~3% INR depreciation
}

In [3]:
records = []

for currency, base_rate in base_rates.items():
    for scenario, adj in scenario_adjustments.items():
        scenario_rate = round(base_rate * (1 + adj), 2)
        
        importer_impact = fx_amount * (scenario_rate - base_rate)
        exporter_impact = fx_amount * (base_rate - scenario_rate)
        it_profit = (fx_amount * scenario_rate) - it_costs
        
        records.append([
            currency,
            scenario,
            scenario_rate,
            importer_impact,
            exporter_impact,
            it_profit
        ])

multi_fx_scenarios = pd.DataFrame(
    records,
    columns=[
        "Currency",
        "Scenario",
        "FX_to_INR_Rate",
        "Importer_Impact_INR",
        "Exporter_Impact_INR",
        "IT_Firm_Profit_INR"
    ]
)

multi_fx_scenarios

,Currency,Scenario,FX_to_INR_Rate,Importer_Impact_INR,Exporter_Impact_INR,IT_Firm_Profit_INR
0,USD,Favorable,81.34,-16600.0,16600.0,213400.0
1,USD,Neutral,83.00,0.0,0.0,230000.0
2,USD,Adverse,85.49,24900.0,-24900.0,254900.0
3,GBP,Favorable,102.90,-21000.0,21000.0,429000.0
4,GBP,Neutral,105.00,0.0,0.0,450000.0
5,GBP,Adverse,108.15,31500.0,-31500.0,481500.0
6,EUR,Favorable,88.20,-18000.0,18000.0,282000.0
7,EUR,Neutral,90.00,0.0,0.0,300000.0
8,EUR,Adverse,92.70,27000.0,-27000.0,327000.0
9,JPY,Favorable,0.55,-100.0,100.0,-594500.0
10,JPY,Neutral,0.56,0.0,0.0,-594400.0
11,JPY,Adverse,0.58,200.0,-200.0,-594200.0

In [4]:
par_records = []

for currency, base_rate in base_rates.items():
    adverse_rate = round(base_rate * 1.03, 2)
    
    par_records.append([
        currency,
        fx_amount * abs(adverse_rate - base_rate)
    ])

profit_at_risk_multi = pd.DataFrame(
    par_records,
    columns=["Currency", "Profit_at_Risk_INR"]
)

profit_at_risk_multi

  Currency  Profit_at_Risk_INR
0      USD             24900.0
1      GBP             31500.0
2      EUR             27000.0
3      JPY               200.0

### Break-Even and Pain Thresholds Across Currencies

Break-even remains the base exchange rate for each currency.
Pain thresholds are defined as a ±3% adverse movement.

In [5]:
thresholds_multi = pd.DataFrame({
    "Currency": list(base_rates.keys()),
    "Break_Even_Rate": list(base_rates.values()),
    "Pain_Threshold_Rate": [round(rate * 1.03, 2) for rate in base_rates.values()]
})

thresholds_multi

  Currency  Break_Even_Rate  Pain_Threshold_Rate
0      USD            83.00                85.49
1      GBP           105.00               108.15
2      EUR            90.00                92.70
3      JPY             0.56                 0.58

In [6]:
def exposure_zone(rate, base_rate):
    if rate <= base_rate:
        return "Safe"
    elif rate <= base_rate * 1.03:
        return "Warning"
    else:
        return "Danger"

multi_fx_scenarios["Exposure_Zone"] = multi_fx_scenarios.apply(
    lambda x: exposure_zone(x["FX_to_INR_Rate"], base_rates[x["Currency"]]),
    axis=1
)

multi_fx_scenarios

,Currency,Scenario,FX_to_INR_Rate,Importer_Impact_INR,Exporter_Impact_INR,IT_Firm_Profit_INR,Exposure_Zone
0,USD,Favorable,81.34,-16600.0,16600.0,213400.0,Safe
1,USD,Neutral,83.00,0.0,0.0,230000.0,Safe
2,USD,Adverse,85.49,24900.0,-24900.0,254900.0,Warning
3,GBP,Favorable,102.90,-21000.0,21000.0,429000.0,Safe
4,GBP,Neutral,105.00,0.0,0.0,450000.0,Safe
5,GBP,Adverse,108.15,31500.0,-31500.0,481500.0,Warning
6,EUR,Favorable,88.20,-18000.0,18000.0,282000.0,Safe
7,EUR,Neutral,90.00,0.0,0.0,300000.0,Safe
8,EUR,Adverse,92.70,27000.0,-27000.0,327000.0,Warning
9,JPY,Favorable,0.55,-100.0,100.0,-594500.0,Safe
10,JPY,Neutral,0.56,0.0,0.0,-594400.0,Safe
11,JPY,Adverse,0.58,200.0,-200.0,-594200.0,Danger

## Multi-Currency Interpretation

The extended analysis demonstrates that the exposure modelling framework is
currency-agnostic. Importers face direct cost increases across all currencies
during INR depreciation, while exporters benefit conditionally.

IT services firms exhibit margin sensitivity regardless of currency, with
exposure magnitude varying based on the base exchange rate.

This generalised structure allows seamless integration with downstream
risk scoring and recommendation modules across multiple currencies.